server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/aco
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        enable_lazy_load_no_trans: true
    show-sql: false
    open-in-view: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO